name: GiveFix
favicon: null
layout_spectrum: 0.5649239595513791
typography_spectrum: 0.6219688369892538
title: GiveFix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2965633668936789
  lightness: 0.1149961487390101
  saturation: 0.2992500117979944
  rhythmicContrast: 0.04664176679216325
purpose: []
