name: GiveFix
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39467
title: GiveFix
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffce54'
    - '#000000'
    - '#ffffff'
    - '#a6a6a6'
    - '#393939'
  brandStrength: 0.2965633668936789
  lightness: 0.1149961487390101
  saturation: 0.2992500117979944
  rhythmicContrast: 0.04664176679216325
purpose: []
